version: "3"

services:

  app:
    image: "swarmtest:${DOCKER_IMAGE_TAG}"
    command: curl http://whoami
    networks:
      - traefik_services
    deploy:
      mode: replicated
      replicas: 2

networks:
  traefik_services:
    external: true
