version: "3"

services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - backend

  worker:
    image: alpine:latest
    command: ping redis
    networks:
      - frontend
      - backend
    depends_on:
      - redis
    # service deployment
    deploy:
      mode: replicated
      replicas: 2
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

networks:
  frontend:
  backend:

volumes:
  redis-data:
