version: "3"

services:
  app:
    image: manomarks/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_services
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.port=8080"

networks:
  traefik_services:
    external: true
