version: "3"

services:
  app:
    image: emilevauge/whoami
    networks:
      - traefik_services
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:whoami.docker.localhost"

networks:
  traefik_services:
    external: true
